### ISSUE TITLE
Emoji Filenames Break The Template

### ISSUE THREAD

**Issue by aidan-gibson** [maximevaillancourt/digital-garden-jekyll-template#106]
**Describe the bug**
Replacing a filename with 😫 will make 😫.md the new index. It will list every single other markdown file in `_notes` as a backlink to it.

**To reproduce**
1. Download vanilla template.
2. Change 안녕하세요.md to 😫.md
3. `bundle install`
4. `bundle exec jekyll serve --livereload`
5. View localhost:4000

**Expected behavior**
Expected to see [index page](https://digital-garden-jekyll-template.netlify.app/). Instead saw 
![image](https://user-images.githubusercontent.com/20917687/159832830-dff26e7e-e5b0-430a-81e4-e5714eb1d5af.png)

**Desktop (please complete the following information):**
 - Operating system: macOS 12.3
 - Ruby version: ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]

**Comment by whoibrar** [comment]
Not a complete solution but you can try this.

As the the current template can already render and link to notes via title property in frontmatter, you can make the file with regular ascii names and title property to link to it.

Instead of  `🚗.md` make `car-emoji.md` and in the front-matter : 

```
title : 🚗
```
Link to the file as [[car-emoji]] or [[🚗]].

**Comment by maximevaillancourt** [comment]
Good catch, thanks for reporting this.

This appears to be a limitation of Jekyll's way of turning a file name into a [slug](https://jekyllrb.com/docs/permalinks/) to create a permalink.

Closing this as there is a good alternative shared above (thank you whoibrar!)
