### ISSUE TITLE
Last updated date is incorrect

### ISSUE THREAD

**Issue by ngm** [maximevaillancourt/digital-garden-jekyll-template#12]
The last updated date on a page appears to show the date of the latest update to *any* page, not the one you are currently viewing.

e.g. 

![image](https://user-images.githubusercontent.com/172324/95979949-5ac61d80-0e14-11eb-9ac5-d4b58b00fcc2.png)

^ shows 14th October

however, looking at the update times on my filesystem:

![image](https://user-images.githubusercontent.com/172324/95980016-73363800-0e14-11eb-8d18-92a637bbd4b5.png)

the corresponding page was last edited 13th October.

**Comment by maximevaillancourt** [comment]
Hey Neil, thanks for raising this. The `Last updated on` feature is powered by the `jekyll-last-modified-at` gem, which relies on the timestamp of the last Git commit of the file - not the filesystem's "last touched" timestamp. I've been running into issues with the gem as well in other scenarios, so I'll look into an alternative solution and update the issue here.

As for your particular issue, it's potentially caused by the use of a Git submodule to point to notes in [`digitalgardeners/digital-garden-jekyll-template`](https://github.com/digitalgardeners/digital-garden-jekyll-template). Because of this, it's possible that the gem has trouble figuring out the actual commit dates of the files. Not sure though.

**Comment by maximevaillancourt** [comment]
I confirm that this is indeed caused by the use of a submodule. I'll contribute to `jekyll-last-modified-at` to make sure it gets commit timestamps from submodules.

**Comment by maximevaillancourt** [comment]
Fix submitted to https://github.com/gjtorikian/jekyll-last-modified-at/pull/82.

**Comment by maximevaillancourt** [comment]
Local fix submitted in https://github.com/digitalgardeners/digital-garden-jekyll-template/pull/1.

**Comment by Am3ra** [comment]
@maximevaillancourt , should this PR be closed then? (Btw, PRs can be linked to issues, might be useful in the future)
