### ISSUE TITLE
notes_graph.json cannot be found, github-pages' build fails

### ISSUE THREAD

**Issue by damienbelveze** [maximevaillancourt/digital-garden-jekyll-template#163]
Hello,

I use your template to make a static website with an Obsidian vault. Thank you very much for having shared your code. 
It worked at the beginning (a month ago) but does not seem to work anymore when I try to push changes to my github repo where all my notes are (under _notes)

Github pages seem to look for a notes_graph.json while only a notes_graph.html is provided: 

"github-pages 228 | Error:  Could not locate the included file 'notes_graph.json' in any of ["/github/workspace/_includes", "/usr/local/bundle/gems/jekyll-theme-primer-0.6.0/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode."

Could you please tell me how to fix that?

Regards,

DB

**Comment by maximevaillancourt** [comment]
`notes_graph.json` is a file that gets automatically generated during the build process of the template (via [this plugin](https://github.com/maximevaillancourt/digital-garden-jekyll-template/blob/1edf1fadaca610eb2eeed207c7a4c3f0e3120ac5/_plugins/bidirectional_links_generator.rb#L102-L106)). The error message you see indicates that `notes_graph.json` wasn't generated, so rendering the site fails because Jekyll expects to find `notes_graph.json` in the `_includes/` directory.

👉 Using GitHub Actions to build your site may resolve this problem (see [this discussion thread](https://github.com/maximevaillancourt/digital-garden-jekyll-template/discussions/144#discussioncomment-5896846)).
