### ISSUE TITLE
github-pages can't satisfy your Gemfile's dependencies

### ISSUE THREAD

**Issue by damienbelveze** [maximevaillancourt/digital-garden-jekyll-template#169]
Hello, 

**Describe the bug**
I have tried to deploy your template as it is from github pages and got the following message: 
github-pages can't satisfy your Gemfile's dependencies.

**To reproduce**
1. I went to your github repo 'digitan-garden-jekyll-template.'
2. Clicked on 'use this template'
3. Once I cloned and renamed it, I went to settings > Pages > deploy from branch, selected "main" and "/root" then clicked on save
4. and got [this error](https://uniren1-my.sharepoint.com/:i:/g/personal/damien_belveze_univ-rennes1_fr/ERz4lTGZv9dEoGK0W3t4VBMBvilhnaaNJvXtPMEuzg-VPg?e=rBTU7h)

What could I do to fix that and deploy your digital garden (first step to use it with my notes)?

Thank you in advance for your help

Damien Belvèze

**Comment by maximevaillancourt** [comment]
Hi Damien,

Just to be clear: are you referring to line 10 in the screenshot you shared? If so, that's only a warning (not an error), and shouldn't cause the build process to fail.

Could you share a screenshot of the rest of the output? (beyond line 32)

In the meantime, you might want to try these potential solutions:
- **Most likely to work**: [Use GitHub Actions to deploy to GitHub Pages](https://github.com/maximevaillancourt/digital-garden-jekyll-template/discussions/144#discussioncomment-5896846)
- Install the [`faraday-retry` gem](https://github.com/lostisland/faraday-retry#installation) in your project (I only suggest this because I see a message about it in your screenshot, I'm not sure it'll change anything but worth a try)
