### ISSUE TITLE
Error in bundle command

### ISSUE THREAD

**Issue by Vasallius** [maximevaillancourt/digital-garden-jekyll-template#18]
Hi, I run the bundle command and get this.

```
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using public_suffix 4.0.4
Using addressable 2.7.0
Using bundler 2.1.4
Using colorator 1.1.0
Using concurrent-ruby 1.1.6
Using eventmachine 1.2.7 (x64-mingw32)
Fetching http_parser.rb 0.6.0
Installing http_parser.rb 0.6.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
C:/tools/ruby24/bin/ruby.exe -I C:/tools/ruby24/lib/ruby/site_ruby/2.4.0 -r
./siteconf20201028-14256-18oa8u4.rb extconf.rb
creating Makefile

current directory:
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR=" clean
current directory:
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR="
make failedNo such file or directory - make "DESTDIR="

Gem files will remain installed in
C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to
C:/tools/ruby24/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/http_parser.rb-0.6.0/gem_make.out

An error occurred while installing http_parser.rb (0.6.0), and Bundler cannot
continue.
Make sure that `gem install http_parser.rb -v '0.6.0' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  jekyll-last-modified-at was resolved to 1.2.1, which depends on
    jekyll was resolved to 4.0.0, which depends on
      em-websocket was resolved to 0.5.1, which depends on
        http_parser.rb
```

I then tried running this **`gem install http_parser.rb -v '0.6.0' --source 'https://rubygems.org/'`**

But I get this:
```
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing http_parser.rb:
        ERROR: Failed to build gem native extension.

    current directory: C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
C:/tools/ruby24/bin/ruby.exe -I C:/tools/ruby24/lib/ruby/site_ruby/2.4.0 -r ./siteconf20201028-16540-rq1qnr.rb extconf.rb
creating Makefile

current directory: C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR=" clean
current directory: C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR="
make failedNo such file or directory - make "DESTDIR="

Gem files will remain installed in C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to C:/tools/ruby24/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/http_parser.rb-0.6.0/gem_make.out
```

I don't know what to do anymore.

**Comment by maximevaillancourt** [comment]
Hey Jed, it looks like you're trying to install Jekyll on Windows and it fails because of the `http_parser.rb` gem. I'm sorry to read that, I haven't tested it on Windows.

As a way to prevent potential future problems, I **highly recommend installing the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about)**, also known as WSL, to use a real Linux environment within Windows and prevent all Windows-related issues. Once WSL is installed, you may try to setup the template there instead.

If you prefer using Windows directly, I found resources that may point you in the right direction:
- [Installation error when installing on a path with spaces using Bundler](https://github.com/tmm1/http_parser.rb/issues/47)
- [Re: Windows 10: Jekyll Installation: “Could note find gem ‘jekyll (~> 4.1.1) x64-ming32’](https://talk.jekyllrb.com/t/re-windows-10-jekyll-installation-could-note-find-gem-jekyll-4-1-1-x64-ming32/5063/9)
- [Setting Up a Ruby Development Environment on Windows](https://raviriley.github.io/tutorial/pinned/setting-up-windows-for-jekyll/)

**Comment by Vasallius** [comment]
Hi, thanks for the recommendation. I would want to install the Windows Subsytem for Linux. However, I'm afraid it might be complicated? What do you also mean by trying to setup the template there instead? Sorry as I am not well-versed in this area. I would love to be helped personally, you may contact me at discord if that's okay with you (Jed#1699) ^_^

**Comment by maximevaillancourt** [comment]
I recommend following this video to install the Windows Subsystem for Linux (WSL): https://www.youtube.com/watch?v=5RTSlby-l9w

Once that's done and you have access to the Linux shell (which you can start with `wsl` in the Start Menu), you'll be able to follow [this tutorial](https://maximevaillancourt.com/blog/setting-up-your-own-digital-garden-with-jekyll) to start setting up the repository in Linux.

**Comment by Am3ra** [comment]
Would this be a `wontfix`, considering it's an issue with bundle and not the repo?

**Comment by maximevaillancourt** [comment]
Correct - specifically, it's an issue with installing `http_parser.rb` on Windows. Best to open an issue in https://github.com/tmm1/http_parser.rb directly.
