### ISSUE TITLE
Would it be possible to add MathJax and MermaidJS Support?

### ISSUE THREAD

**Issue by phibr0** [maximevaillancourt/digital-garden-jekyll-template#34]
I'm using Obsidian as my main Editor and use both MathJax and Mermaid quite frequently

**Comment by xplosionmind** [comment]
By default, Jekyll doesn't support neither [MathJax](https://kramdown.gettalong.org/math_engine/mathjax.html) or Mermaid, since it uses Kramdown as a Markdown converter engine.

One thing you can do by yourself is adding to your repository plugins which add support for the syntax you need.

[This](https://github.com/jasonbellamy/jekyll-mermaid) is the plugin for Mermaid; I couldn't find one for Latex support.

**Comment by phibr0** [comment]
Hm.. for the mermaid plugin my mermaid block need to be inside
{mermaid}
mermaid stuff
{mermaid}

and not like it is in obsidian:
\```mermaid
mermaid stuff
\```

But thanks for your help 👍
