### ISSUE TITLE
Bi-directional links not working

### ISSUE THREAD

**Issue by dpvtank** [maximevaillancourt/digital-garden-jekyll-template#4]
I finally managed to get the website working (you can see it at https://mind.dtank.co)

It however is not able to find the bi-directional links on pages. I'm using just a forked version of the repo, with no new notes. So I am unsure why this might be happening.

Any ideas?

Here is the repo: https://github.com/dpvtank/digital-garden

**Comment by maximevaillancourt** [comment]
Thanks for the report. Looking at mind.dtank.co, it looks like the [custom bidirectional link generator](https://github.com/dpvtank/digital-garden/blob/master/_plugins/bidirectional_links_generator.rb) is not picked up when Jekyll builds the static website.

How do you deploy the repository? Straight from GitHub to Netlify? Local `jekyll build` then upload somewhere? There is likely an issue in the build process that prevents the custom generator from working properly.

**Comment by dpvtank** [comment]
I deployed it from Netlify. I don't actually know how to use local builds and push onto github.

Here is the Netlify link: https://dtank-digital-garden.netlify.app

Interestingly enough, the bi-directional links work just fine there.

**Comment by maximevaillancourt** [comment]
Do you mean that you have a custom domain (mind.dtank.co) on your Netlify site? If so, I would assume that bidirectional links work fine on the custom domain, just like on the netlify.app domain.

If you're not using a custom domain on your Netlify deploy, I'm not sure I understand where the site is deployed. Is it on different cloud provider / VPS / personal server?

**Comment by dpvtank** [comment]
I guess this reveals the limits of my technical knowledge.

I followed the instructions to fork the site on Github and then deploy it via Netlify that was on your instructions. I followed the instructions to the T. 

The link I provided above (https://dtank-digital-garden.netlify.app) is the link that netlify gives me when I logged in to dig in there since you had suggested there might be an issue with how things are building. 

But the site is hosted on github, and I have a custom domain setup there (mind.dtank.co). On the custom domain of the site, the bi-directional links don't work. But on the Netlify link, it works. I have no idea why.

I am definitely not hosting this anywhere else.

Is this making sense? I'm sorry, but I am new to Github and Jekyll and Netlify and I am still learning, so I hope this isn't confusing.

**Comment by maximevaillancourt** [comment]
> But the site is hosted on github, and I have a custom domain setup there (mind.dtank.co). 

That's the issue. GitHub Pages [doesn't support custom plugins](https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll#plugins). Since this site generates bi-directional links using a [custom plugin I wrote](https://github.com/maximevaillancourt/digital-garden-jekyll-template/blob/master/_plugins/bidirectional_links_generator.rb), GitHub Pages won't generate them. Netlify supports custom plugins, so my custom generator works there.

To solve your issue, you should remove your custom domain from GitHub Pages, and instead set it as a [custom domain on your Netlify site ](https://docs.netlify.com/domains-https/custom-domains/#assign-a-domain-to-a-site)(https://dtank-digital-garden.netlify.app). You'll also need to update your DNS entries.

Let me know if this helps! 🙂

**Comment by dpvtank** [comment]
That's it! That takes care of it! Thank you!
