### ISSUE TITLE
Are the "links to this note" limited to two?

### ISSUE THREAD

**Issue by kevindstevens1010** [maximevaillancourt/digital-garden-jekyll-template#6]
Hi - are "links to this note" being limited to two?

Example: here is my bookshelf page: https://stupefied-tereshkova-10b682.netlify.app/bookshelf

And here is "How to Take Smart Notes" - also tagged bookshelf - https://stupefied-tereshkova-10b682.netlify.app/how%20to%20take%20smart%20notes

How to Take Smart Notes is tagged, but not showing up. I'd like to set this to an unlimited number so that all notes linked to it show up.

**Comment by maximevaillancourt** [comment]
Hi Kevin, thanks for opening this issue. It may be related to this GitHub issue, which I just pushed a fix for in https://github.com/maximevaillancourt/digital-garden-jekyll-template/commit/d8b794908ffb54f2b9be1d2fa96beda573b76380.

Depending on how familiar you are with Git and GitHub, you may choose to [sync your forked repository with the one we're commenting on](https://dev.to/jeremy/how-to-sync-your-fork-with-the-parent-repository-3ok1) to get the code I just added, or simply copy the code from the commit I shared in the paragraph above, and directly add it to your fork.

Feel free to close the issue if this resolves your issue. Let me know otherwise 🙂

**Comment by kevindstevens1010** [comment]
That worked!  Thank you.  

One last request, could you bring the CSS for posts on your blog into the notes theme?

I like how your bullets are indented, and organized there - it would be great to have that formatting in notes.

**Comment by maximevaillancourt** [comment]
Updated in https://github.com/maximevaillancourt/digital-garden-jekyll-template/commit/af8b29d77da572ef1dc69c6812c07f77ece72c3b. Cheers!
