### ISSUE TITLE
Cannot build template on ARM-based M1 MacBook

### ISSUE THREAD

**Issue by owenvachell** [maximevaillancourt/digital-garden-jekyll-template#71]
Getting the attached error when following the setup guide. The bundle command had been run previously before this latest attempt but you won't see it in this txt file.
[Terminal Saved Output.txt](https://github.com/maximevaillancourt/digital-garden-jekyll-template/files/6850061/Terminal.Saved.Output.txt)

**Comment by danbartlett** [comment]
Are you using an M1 Macbook? What does `uname -a` return for you?

**Comment by owenvachell** [comment]
Yeah it's an M1 MacBook. I assumed that the uname request was to clarify this, but below is what gets returned: 

`Darwin Owens-MacBook-Air-2.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64`

**Comment by danbartlett** [comment]
The main error is `no suitable image found .... wrong architecture`. I got a lot of these errors after getting set up on the M1. Sometimes different terminals set the arch differently, hence the `uname` check—it seems to be set correctly. I still have issues with this changing inside of `tmux` sessions, which results in some gems being installed as x86, some as arm64. That then leads to `wrong architecture` errors. Some people have overcome this issue [this way](https://stackoverflow.com/a/66102923/1794732); it might take some digging, but right now I don't think the error is specific to this gem.

**Comment by maximevaillancourt** [comment]
Thanks for the report @owenvachell. Looking at the terminal output you shared, it looks like the issue is triggered by the `jekyll-last-modified-at` gem, which I use in this template to show the datetime at which a note was last modified.

I suggest removing this gem from your local development setup (by removing it from your local `Gemfile`) and removing its usages to see if it changes anything. :slightly_smiling_face:

**Comment by owenvachell** [comment]
Thank you. That's fixed the issue.
